import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import pstyles from "@/styles/Projects.module.scss"
import NavBar from "./components/navbar";
import Projects from './components/projects';
import Experience from "./components/experience";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mia Kelly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <div
            className={styles.card} 
            id="about"
          >
            <h2>
              About Me
            </h2>
            <p>
            Hello! I am a student pursuing computer science and cybersecurity at Michigan Technological University. Getting involved in student organizations such as the Networking and Computing Student Association (NCSA) and IT Oxygen Enterprise, I've cultivated a rich tapestry of skills spanning full-stack development, machine learning, and cloud technologies. Beyond honing my technical expertise, my this has given me the opportunity to mentor younger students towards their own success.
            </p>
          </div>
          <Experience />        
          <Projects/>
          <div 
            className={styles.card}
            id="contact"
          >
            <h2>Contact</h2>
            <Image 
              src="/envelope.svg"
              width={30}
              height={30}
            />
            <p><a href="mailto:mykelly@mtu.edu">mykelly@mtu.edu</a></p>
            <br/>
            <Image 
              src="/linkedin.svg"
              width={30}
              height={30}
            />
            <p><a href="https://www.linkedin.com/in/mia-kelly-mtu/">LinkedIn</a></p>
          </div>
        </div>
      </main>
    </>
  );
}
